//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;

    public partial class DETAIL
    {
        public long DETCODE { get; set; }
        public string MASCODE { get; set; }
        public string CAMERACODE { get; set; }
        public string FEATURE { get; set; }

        public virtual MASTER MASTER { get; set; }
    }
}
